export type Country = { name: string; iso2: string; dialCode: string };

export const COUNTRIES: Country[] = [
  { name: 'France', iso2: 'FR', dialCode: '+33' },
  { name: 'Belgique', iso2: 'BE', dialCode: '+32' },
  { name: 'Suisse', iso2: 'CH', dialCode: '+41' },
  { name: 'Luxembourg', iso2: 'LU', dialCode: '+352' },
  { name: 'Monaco', iso2: 'MC', dialCode: '+377' },
  { name: 'Andorre', iso2: 'AD', dialCode: '+376' },
  { name: 'Espagne', iso2: 'ES', dialCode: '+34' },
  { name: 'Portugal', iso2: 'PT', dialCode: '+351' },
  { name: 'Italie', iso2: 'IT', dialCode: '+39' },
  { name: 'Allemagne', iso2: 'DE', dialCode: '+49' },
  { name: 'Pays-Bas', iso2: 'NL', dialCode: '+31' },
  { name: 'Royaume-Uni', iso2: 'GB', dialCode: '+44' },
  { name: 'Irlande', iso2: 'IE', dialCode: '+353' },
  { name: 'États-Unis', iso2: 'US', dialCode: '+1' },
  { name: 'Canada', iso2: 'CA', dialCode: '+1' },
  { name: 'Mexique', iso2: 'MX', dialCode: '+52' },
  { name: 'Brésil', iso2: 'BR', dialCode: '+55' },
  { name: 'Argentine', iso2: 'AR', dialCode: '+54' },
  { name: 'Chili', iso2: 'CL', dialCode: '+56' },
  { name: 'Colombie', iso2: 'CO', dialCode: '+57' },
  { name: 'Pérou', iso2: 'PE', dialCode: '+51' },
  { name: 'Uruguay', iso2: 'UY', dialCode: '+598' },
  { name: 'Paraguay', iso2: 'PY', dialCode: '+595' },
  { name: 'Bolivie', iso2: 'BO', dialCode: '+591' },
  { name: 'Venezuela', iso2: 'VE', dialCode: '+58' },
  { name: 'Maroc', iso2: 'MA', dialCode: '+212' },
  { name: 'Algérie', iso2: 'DZ', dialCode: '+213' },
  { name: 'Tunisie', iso2: 'TN', dialCode: '+216' },
  { name: 'Libye', iso2: 'LY', dialCode: '+218' },
  { name: 'Égypte', iso2: 'EG', dialCode: '+20' },
  { name: 'Sénégal', iso2: 'SN', dialCode: '+221' },
  { name: 'Côte d’Ivoire', iso2: 'CI', dialCode: '+225' },
  { name: 'Cameroun', iso2: 'CM', dialCode: '+237' },
  { name: 'Gabon', iso2: 'GA', dialCode: '+241' },
  { name: 'Congo (Rép.)', iso2: 'CG', dialCode: '+242' },
  { name: 'Congo (RDC)', iso2: 'CD', dialCode: '+243' },
  { name: 'Bénin', iso2: 'BJ', dialCode: '+229' },
  { name: 'Togo', iso2: 'TG', dialCode: '+228' },
  { name: 'Mali', iso2: 'ML', dialCode: '+223' },
  { name: 'Niger', iso2: 'NE', dialCode: '+227' },
  { name: 'Burkina Faso', iso2: 'BF', dialCode: '+226' },
  { name: 'Guinée', iso2: 'GN', dialCode: '+224' },
  { name: 'Guinée-Bissau', iso2: 'GW', dialCode: '+245' },
  { name: 'Gambie', iso2: 'GM', dialCode: '+220' },
  { name: 'Sierra Leone', iso2: 'SL', dialCode: '+232' },
  { name: 'Libéria', iso2: 'LR', dialCode: '+231' },
  { name: 'Kenya', iso2: 'KE', dialCode: '+254' },
  { name: 'Ouganda', iso2: 'UG', dialCode: '+256' },
  { name: 'Tanzanie', iso2: 'TZ', dialCode: '+255' },
  { name: 'Éthiopie', iso2: 'ET', dialCode: '+251' },
  { name: 'Somalie', iso2: 'SO', dialCode: '+252' },
  { name: 'Rwanda', iso2: 'RW', dialCode: '+250' },
  { name: 'Burundi', iso2: 'BI', dialCode: '+257' },
  { name: 'Madagascar', iso2: 'MG', dialCode: '+261' },
  { name: 'Maurice', iso2: 'MU', dialCode: '+230' },
  { name: 'Seychelles', iso2: 'SC', dialCode: '+248' },
  { name: 'Réunion', iso2: 'RE', dialCode: '+262' },
  { name: 'Mayotte', iso2: 'YT', dialCode: '+262' },
  { name: 'Afrique du Sud', iso2: 'ZA', dialCode: '+27' },
  { name: 'Nigeria', iso2: 'NG', dialCode: '+234' },
  { name: 'Ghana', iso2: 'GH', dialCode: '+233' },
  { name: 'Zimbabwe', iso2: 'ZW', dialCode: '+263' },
  { name: 'Zambie', iso2: 'ZM', dialCode: '+260' },
  { name: 'Botswana', iso2: 'BW', dialCode: '+267' },
  { name: 'Namibie', iso2: 'NA', dialCode: '+264' },
  { name: 'Angola', iso2: 'AO', dialCode: '+244' },
  { name: 'Mozambique', iso2: 'MZ', dialCode: '+258' },
  { name: 'Émirats arabes unis', iso2: 'AE', dialCode: '+971' },
  { name: 'Arabie saoudite', iso2: 'SA', dialCode: '+966' },
  { name: 'Qatar', iso2: 'QA', dialCode: '+974' },
  { name: 'Koweït', iso2: 'KW', dialCode: '+965' },
  { name: 'Bahreïn', iso2: 'BH', dialCode: '+973' },
  { name: 'Oman', iso2: 'OM', dialCode: '+968' },
  { name: 'Jordanie', iso2: 'JO', dialCode: '+962' },
  { name: 'Liban', iso2: 'LB', dialCode: '+961' },
  { name: 'Turquie', iso2: 'TR', dialCode: '+90' },
  { name: 'Iran', iso2: 'IR', dialCode: '+98' },
  { name: 'Irak', iso2: 'IQ', dialCode: '+964' },
  { name: 'Israël', iso2: 'IL', dialCode: '+972' },
  { name: 'Palestine', iso2: 'PS', dialCode: '+970' },
  { name: 'Inde', iso2: 'IN', dialCode: '+91' },
  { name: 'Pakistan', iso2: 'PK', dialCode: '+92' },
  { name: 'Bangladesh', iso2: 'BD', dialCode: '+880' },
  { name: 'Sri Lanka', iso2: 'LK', dialCode: '+94' },
  { name: 'Népal', iso2: 'NP', dialCode: '+977' },
  { name: 'Bhoutan', iso2: 'BT', dialCode: '+975' },
  { name: 'Maldives', iso2: 'MV', dialCode: '+960' },
  { name: 'Chine', iso2: 'CN', dialCode: '+86' },
  { name: 'Japon', iso2: 'JP', dialCode: '+81' },
  { name: 'Corée du Sud', iso2: 'KR', dialCode: '+82' },
  { name: 'Corée du Nord', iso2: 'KP', dialCode: '+850' },
  { name: 'Taïwan', iso2: 'TW', dialCode: '+886' },
  { name: 'Hong Kong', iso2: 'HK', dialCode: '+852' },
  { name: 'Singapour', iso2: 'SG', dialCode: '+65' },
  { name: 'Malaisie', iso2: 'MY', dialCode: '+60' },
  { name: 'Indonésie', iso2: 'ID', dialCode: '+62' },
  { name: 'Philippines', iso2: 'PH', dialCode: '+63' },
  { name: 'Thaïlande', iso2: 'TH', dialCode: '+66' },
  { name: 'Vietnam', iso2: 'VN', dialCode: '+84' },
  { name: 'Cambodge', iso2: 'KH', dialCode: '+855' },
  { name: 'Laos', iso2: 'LA', dialCode: '+856' },
  { name: 'Australie', iso2: 'AU', dialCode: '+61' },
  { name: 'Nouvelle-Zélande', iso2: 'NZ', dialCode: '+64' },
  { name: 'Fidji', iso2: 'FJ', dialCode: '+679' },
  { name: 'Polynésie française', iso2: 'PF', dialCode: '+689' },
  { name: 'Nouvelle-Calédonie', iso2: 'NC', dialCode: '+687' },
  { name: 'Wallis-et-Futuna', iso2: 'WF', dialCode: '+681' },
  { name: 'Papouasie-Nouvelle-Guinée', iso2: 'PG', dialCode: '+675' },
  { name: 'Russie', iso2: 'RU', dialCode: '+7' },
  { name: 'Ukraine', iso2: 'UA', dialCode: '+380' },
  { name: 'Biélorussie', iso2: 'BY', dialCode: '+375' },
  { name: 'Pologne', iso2: 'PL', dialCode: '+48' },
  { name: 'Tchéquie', iso2: 'CZ', dialCode: '+420' },
  { name: 'Slovaquie', iso2: 'SK', dialCode: '+421' },
  { name: 'Hongrie', iso2: 'HU', dialCode: '+36' },
  { name: 'Roumanie', iso2: 'RO', dialCode: '+40' },
  { name: 'Bulgarie', iso2: 'BG', dialCode: '+359' },
  { name: 'Grèce', iso2: 'GR', dialCode: '+30' },
  { name: 'Chypre', iso2: 'CY', dialCode: '+357' },
  { name: 'Croatie', iso2: 'HR', dialCode: '+385' },
  { name: 'Serbie', iso2: 'RS', dialCode: '+381' },
  { name: 'Bosnie-Herzégovine', iso2: 'BA', dialCode: '+387' },
  { name: 'Monténégro', iso2: 'ME', dialCode: '+382' },
  { name: 'Macédoine du Nord', iso2: 'MK', dialCode: '+389' },
  { name: 'Albanie', iso2: 'AL', dialCode: '+355' },
  { name: 'Islande', iso2: 'IS', dialCode: '+354' },
  { name: 'Norvège', iso2: 'NO', dialCode: '+47' },
  { name: 'Suède', iso2: 'SE', dialCode: '+46' },
  { name: 'Finlande', iso2: 'FI', dialCode: '+358' },
  { name: 'Danemark', iso2: 'DK', dialCode: '+45' },
  { name: 'Estonie', iso2: 'EE', dialCode: '+372' },
  { name: 'Lettonie', iso2: 'LV', dialCode: '+371' },
  { name: 'Lituanie', iso2: 'LT', dialCode: '+370' },
  { name: 'Slovénie', iso2: 'SI', dialCode: '+386' },
  { name: 'Autriche', iso2: 'AT', dialCode: '+43' },
  { name: 'Malte', iso2: 'MT', dialCode: '+356' },
  { name: 'Liechtenstein', iso2: 'LI', dialCode: '+423' },
  { name: 'Saint-Marin', iso2: 'SM', dialCode: '+378' },
];

export function findCountryByName(name: string): Country | undefined {
  const norm = name.trim().toLowerCase();
  return COUNTRIES.find((c) => c.name.toLowerCase() === norm);
}

export function iso2ToFlag(iso2: string): string {
  if (!iso2) return '';
  const code = iso2.toUpperCase();
  if (code.length !== 2) return '';
  const A = 0x1f1e6; // Regional Indicator Symbol Letter A
  const base = 'A'.charCodeAt(0);
  const chars = Array.from(code).map((ch) => String.fromCodePoint(A + (ch.charCodeAt(0) - base)));
  return chars.join('');
}
